spring:
  datasource:
    username: root
    password: terminal
    url: jdbc:mysql://localhost:3306/meetingdata?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    time-zone: UTC
#    time-zone: UTC GMT+8